pipeline:
  name: No-Input-Remote
  identifier: NoInputRemote
  projectIdentifier: Pankaj_Git_Sync
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: S1
        identifier: S1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo Hello World
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
